export const GET_MOVIE_DETAIL_PENDING = 'GET_MOVIE_DETAIL_PENDING';
export const GET_MOVIE_DETAIL_SUCCESS = 'GET_MOVIE_DETAIL_SUCCESS';
export const GET_MOVIE_DETAIL_FAIL = 'GET_MOVIE_DETAIL_FAIL';

export const FETCH_SEARCH_MOVIE_PENDING = 'FETCH_SEARCH_MOVIE_PENDING';
export const FETCH_SEARCH_MOVIE_SUCCESS = 'FETCH_SEARCH_MOVIE_SUCCESS';
export const FETCH_SEARCH_MOVIE_FAIL = 'FETCH_SEARCH_MOVIE_FAIL';

export const GET_GENRES_LIST_PENDING = 'GET_GENRES_LIST_PENDING';
export const GET_GENRES_LIST_SUCCESS = 'GET_GENRES_LIST_SUCCESS';
export const GET_GENRES_LIST_FAIL = 'GET_GENRES_LIST_FAIL';

export const GET_NOW_PLAYING_MOVIES_PENDING = 'GET_NOW_PLAYING_MOVIES_PENDING';
export const GET_NOW_PLAYING_MOVIES_SUCCESS = 'GET_NOW_PLAYING_MOVIES_SUCCESS';
export const GET_NOW_PLAYING_MOVIES_FAIL = 'GET_NOW_PLAYING_MOVIES_FAIL';
