export const GET_MOVIE_DETAIL_PENDING = 'GET_MOVIE_DETAIL_PENDING';
export const GET_MOVIE_DETAIL_SUCCESS = 'GET_MOVIE_DETAIL_SUCCESS';
export const GET_MOVIE_DETAIL_FAIL = 'GET_MOVIE_DETAIL_FAIL';

export const FETCH_SEARCH_MOVIE_PENDING = 'FETCH_SEARCH_MOVIE_PENDING';
export const FETCH_SEARCH_MOVIE_SUCCESS = 'FETCH_SEARCH_MOVIE_SUCCESS';
export const FETCH_SEARCH_MOVIE_FAIL = 'FETCH_SEARCH_MOVIE_FAIL';
